"""empty message

Revision ID: 03490b6f744e
Revises: f3c009f90d9e
Create Date: 2019-04-02 11:31:59.179392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03490b6f744e'
down_revision = 'f3c009f90d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('middle_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_middle_name'), 'user', ['middle_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_middle_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_column('user', 'middle_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
