"""empty message

Revision ID: 14e0f9c5db3a
Revises: 03490b6f744e
Create Date: 2019-04-05 18:09:49.769629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e0f9c5db3a'
down_revision = '03490b6f744e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('user', sa.Column('profilepicture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profilepicture')
    op.drop_column('user', 'image_url')
    # ### end Alembic commands ###
