"""empty message

Revision ID: 757b49c77662
Revises: 6af3389a2870
Create Date: 2018-12-03 11:40:36.775188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757b49c77662'
down_revision = '6af3389a2870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_business_id'), 'business', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_id'), table_name='business')
    # ### end Alembic commands ###
