"""empty message

Revision ID: 8b500b737625
Revises: ac64e79076d5
Create Date: 2019-03-31 17:15:02.001522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b500b737625'
down_revision = 'ac64e79076d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_user_location'), 'user', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_location'), table_name='user')
    op.drop_column('user', 'location')
    # ### end Alembic commands ###
