"""empty message

Revision ID: cda56ddacee8
Revises: 8b500b737625
Create Date: 2019-03-31 17:56:04.573837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda56ddacee8'
down_revision = '8b500b737625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('preference', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=False)
    op.create_index(op.f('ix_user_preference'), 'user', ['preference'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preference'), table_name='user')
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_column('user', 'preference')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
